version: '3.3'
services:
  client:
    image: myclient:latest
    ports:
     - "3100:3000"
    command: "npm --prefix /usr/src/app run start"
    volumes:
     - "./client:/usr/src/app"
  server:
    image: myserver:latest
    ports:
     - "8080:80"
    volumes:
     - "./server:/var/www"
